### ISSUE TITLE
Cooperation Strategy with Map of tomorrow

### ISSUE THREAD

**Issue by wellemut** [FinnWoelm/globalgoals.directory#3]
Hello @FinnWoelm 
I just found out about your Map: https://beta.globalgoals.directory/karte and was wondering, about your future strategies and features?
Do you know the Kartevonmorgen.org? We are also trying to map all SDG Initiatives and Projects. Some first examples can be found here: https://blog.vonmorgen.org/sdg-mapping/

As I can see, you just started with your map. If your entries will be on a creative commons basis, we can share the same set of date: https://github.com/kartevonmorgen/openfairdb

And our fontend code is really meant to be modificable. it also would be an option to work on the same code: https://github.com/kartevonmorgen/kartevonmorgen.ts

What do you think about it?

**Comment by FinnWoelm** [comment]
Hi @wellemut,

Thanks for finding us and for reaching out. Have heard a lot about Karte von Morgen over the past months and it's an absolute pleasure to connect with you!

I had no idea you were also mapping initiatives to the SDGs now. That's  phenomenal. We should absolutely talk and see how we can collaborate and work together. There is also a big project by the GIZ / Nachhaltigkeitsrat on the way that will be mapping sustainability initiatives in Germany to the SDGs. If you don't know about this yet, you definitely should. Here is a link (https://ausschreibungen.giz.de/Satellite/public/company/project/CXTRYY6YNT7/de/documents) but happy to share a lot more with you in a call. PS: Karte von Morgen is also mentioned in the tender documents in a couple places 😊

I just sent you an email, so that we can set up a call if you are interested!

**Comment by FinnWoelm** [comment]
Hi @wellemut, great speaking yesterday! Very clear overlap between our missions and visions — let's see how we can collaborate in the near- and long-term future! We will definitely keep you posted on our work and progress :)
